language: php
sudo: required
dist: trusty
addons:
    apt:
        packages:
        - jpegoptim
        - libjpeg-progs
        - optipng
cache:
    timeout: 86400
    bundler: true
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.cache/pip
        - $HOME/.cache/yarn
        - $HOME/.npm
        - tmp/pear/download/
        - vendor/
php:
    # - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
matrix:
    allow_failures:
        - php: hhvm
        - php: 7.1
    include:
        # - php: 5.3
        #   env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 5.6
          env: DEPENDENCIES=dev
before_script:
    - phpenv config-rm xdebug.ini
    - phpenv rehash
    # os deps
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get dist-upgrade -y
    # php deps
    - travis_retry composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - travis_retry composer update $COMPOSER_FLAGS
    # node deps
    - travis_retry npm update -g
    - travis_retry npm install uglify-js@1 && mkdir -p vendor/uglifyjs && mv node_modules vendor/uglifyjs
    - travis_retry npm install
    - export NODE_VERSION=$(node -v | egrep -o "[0-9]+.[0-9]+.[0-9]+")
    - export UGLIFYJS_BIN=vendor/uglifyjs/node_modules/uglify-js/bin/uglifyjs
    - if [[ "$NODE_VERSION" =~ ^0.[0-9].[0-9]+$|^0.10.[0-9]+$|^0.11.[0-9]$|^0.11.1[0-2]$ ]]; then export AUTOPREFIXER_BIN=node_modules/.bin/autoprefixer; else export AUTOPREFIXER_BIN=node_modules/.bin/autoprefixer-cli; fi;
    # java deps
    - mkdir -p vendor/java
    - export CLOSURE_JAR=vendor/java/compiler/compiler.jar
    - export GSS_JAR=vendor/java/closure-stylesheets.jar
    - export CSSEMBED_JAR=vendor/java/cssembed.jar
    - export YUI_COMPRESSOR_JAR=vendor/java/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar
    - if [ ! -e $CLOSURE_JAR ]; then wget http://dl.google.com/closure-compiler/compiler-latest.zip && unzip compiler-latest.zip -d vendor/java/compiler && mv vendor/java/compiler/closure-compiler-*.jar vendor/java/compiler/compiler.jar; fi
    - if [ ! -e $GSS_JAR ]; then wget https://github.com/google/closure-stylesheets/releases/download/v1.4.0/closure-stylesheets.jar -P vendor/java; fi
    - if [ ! -e $CSSEMBED_JAR ]; then wget https://github.com/packagist/cssembed-bin/raw/master/bin/cssembed.jar -P vendor/java; fi
    - if [ ! -e $YUI_COMPRESSOR_JAR ]; then wget http://yui.zenfs.com/releases/yuicompressor/yuicompressor-2.4.7.zip && unzip yuicompressor-2.4.7.zip -d vendor/java; fi
    # ruby deps
    - travis_retry bundle install
    # other deps
    - export DART_BIN=vendor/dart-sdk/bin/dart2js
    - export PNGOUT_BIN=vendor/pngout-20130221-linux/x86_64/pngout
    - if [ ! -e $DART_BIN ]; then wget -q http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip && unzip dartsdk-linux-x64-release.zip && mv dart-sdk vendor; fi
    - if [ ! -e $PNGOUT_BIN ]; then wget -q http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz && tar -xzf pngout-20130221-linux.tar.gz && mv pngout-20130221-linux vendor; fi
script: ./bin/phpunit -v
